### PR TITLE
master

### PR DESCRIPTION
**Pull request by konsultaner**
make custom styles possible

### CODE REVIEW

**Comment by rpdasilva** [comment]
Thanks! Looks pretty good. Currently on vacation until the beginning of start of next week. Will give it a more thorough look then

**Comment by konsultaner** [comment]
thank you :) would be nice to see this feature, because [angular-material](https://material.angularjs.org/latest/) adds some weired styles to the dom that make it impossible to print in portrait format.

**Comment by rpdasilva** [comment]
After looking through your PR, I think the feature is both valid and valuable. I do see some room for improvement however. For example, rather than having `opts.styles` doing double-duty for both inline styles and stylesheets, I think it makes sense to extend opts to also allow stylesheet overrides (something like `opts.stylesheets`).

I'd like to do some further work on top of what you've done. I'll merge this in and have a new release with this feature in the next day or two

**Comment by konsultaner** [comment]
Thank you!

**Comment by rpdasilva** [comment]
@konsultaner: New release should be up on npm `print-html-element@0.5.1`

**Pull request merged**
